# Generated by Django 3.1.1 on 2020-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearly', '0003_wear'),
    ]

    operations = [
        migrations.AddField(
            model_name='wear',
            name='style',
            field=models.TextField(default='', null=True),
        ),
    ]
